version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-dev:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
volumes:
  postgres-dev:
    driver: local